### ISSUE TITLE
will not let me commit so here is a example "database_configuration.json" that needs authentication

### ISSUE THREAD

**Issue by necroscope** [rnpenguin/cgm-remote-monitor#13]
{
    "url": "mongodb://administratoruser:password@dsacct.mongolab.com:33757/dbname",
    "collection": "thecollectioname"
}

I also added a wiki to this project and have put this in the FAQ section.  Plus I wrote an article on forecasting.  Enjoy!

**Comment by rnpenguin** [comment]
Added a link to the wiki, thanks!
