### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by necroscope** [rnpenguin/cgm-remote-monitor#14]
In the  README.md file please reference the the github wiki for troubleshooting.
I am working hard to build out the wiki for this project.  The link to your wiki is

https://github.com/rnpenguin/cgm-remote-monitor/wiki

Thank you for this outstanding work!

**Comment by TC2013** [comment]
Apparently Cunningham should have also volunteered to be the acting RL too ;)

**Comment by rnpenguin** [comment]
Nice, I placed the link and did some format/spelling fixes.
