### ISSUE TITLE
node crashes a lot when mongolabs has issues.

### ISSUE THREAD

**Issue by necroscope** [rnpenguin/cgm-remote-monitor#15]
I noticed node crashes a fair amount.  My Linux instance crashes when I lose connectivity to mongolabs. Mongolabs went down a lot during this whole heartbleed scare. So I now have node or nightscout set to auto restart when it crashes using forever. I think we should add forever into the package.json and make it a part of nightscout.  Just something to consider.  Although it might be a pain when developing.  I tested it on Linux and windows and it works.  Here is my wiki entry on how to install it.
https://github.com/rnpenguin/cgm-remote-monitor/wiki/RESTART-NODE-AUTOMATICALLY

**Comment by rnpenguin** [comment]
Forever is an option, but there really should be some more robust error
handling, please create a separate issue for this for investigation.  Also,
using a service like Azure or Heroku restarts it for you automatically when
it crashes.
