### ISSUE TITLE
Firefox does not render the graphs correctly

### ISSUE THREAD

**Issue by necroscope** [rnpenguin/cgm-remote-monitor#19]
Hi,
I made a wiki entry on what browsers work best so this is a minor issue. The problem is that firefox is very strict when it comes to date strings and invalid dates.  So I believe this prevents the graphs from working correctly in firefox.  It could be something else with firefox but I am investigating it from this approach.  I will let you know if I find something to fix as a result.

**Comment by rnpenguin** [comment]
@necroscope was this fixed via #24 ?

**Comment by rnpenguin** [comment]
Fixed via #24.
