### ISSUE TITLE
panning prediction

### ISSUE THREAD

**Issue by ldesboro** [rnpenguin/cgm-remote-monitor#3]
When bottom "context" view is panned, 1) the top "focus" view should include the vertical "current time" line and the 30 minute ahead prediction, 2) the time in the upper left hand corner should change dynamically to coincide with the vertical "current time" line, and 3) the blood glucose in the upper right hand corner should change dynamically to coincide with the vertical "current time" line.

**Comment by rnpenguin** [comment]
Closed via #25.
