### ISSUE TITLE
Conversion from mg/dl to mmmol/l

### ISSUE THREAD

**Issue by SugarBots** [rnpenguin/cgm-remote-monitor#33]
Is there any chance of adding a config preference to convert the output data to mmol/l? I imagine it would need to happen on the monitor side rather than uploader...

**Comment by rnpenguin** [comment]
Yes, I would like to adding a bootstrap config tabs that would allow for this conversion.  It may or may need to have changes of both the monitor and uploader.  We would need to include a units property in the database so we could know the current units being read from the database.  I will leave this open as a enhancement to be implemented, but in the mean time you could implement in locally and do the conversion yourself until it gets completed.

**Comment by rnpenguin** [comment]
closing, using community maintained fork at https://github.com/nightscout/cgm-remote-monitor.  See https://github.com/nightscout/cgm-remote-monitor/issues/6.
