### ISSUE TITLE
README for new users

### ISSUE THREAD

**Issue by scottleibrand** [rnpenguin/cgm-remote-monitor#8]
I cloned the repo and went looking for where to put the data, but couldn't find any way to populate it.  The README says it reads a CSV, but none of the code references one.  Perhaps I need to be setting up and populating some sort of DB?  I found a few references in old commit comments, but couldn't find anything in the code that actually indicates where it's trying to pull the data from.

Could we put together some basic instructions for new users?  I'd be happy to write something up if someone can give me enough pointers to get going.

**Comment by rnpenguin** [comment]
Sorry about that, I will update it tonight with a good overview :)

**Comment by rnpenguin** [comment]
I updated the README and will add more later.  Any immediate comments?

**Comment by troggy** [comment]
Will be good to have easy way to create database with test data to start hacking instantly.

**Comment by rnpenguin** [comment]
I agree, but I feel that is a new issue and that this can be closed and a new enhancement can be opened.  README is ok now, and can be updated as need be.
